package com.mycompany.mealthymeplanner;

import com.codename1.components.SpanLabel;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.spinner.Picker;
import com.codename1.ui.table.TableLayout;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MealThymePlanner {

    private Form currentForm;
    private Form previousForm;
    private Resources theme;
    private Form mainMenuForm;
    private Form futurePlanningForm;
    private Form savedRecipesForm;
    private Form newUserForm;
    private Form favoriteCuisinesForm;
    private Form allergiesForm;
    private Form myRecipesForm;
    private Form addCustomRecipeForm;
    private Form favoriteRecipesForm;
    private Form profileForm;

    private User currentUser = new User();
    private ArrayList<String> cuisineTypes = new ArrayList<>(Arrays.asList("Italian", "Mexican", "American", "Asian", "African", "Middle Eastern"));

    public void setMainMenuForm() {
        Form tempForm = new Form("Main Menu", new GridLayout(4, 2));
        Button recommended = new Button("Recommended For You");
        Button savedRecipesButton = new Button("Saved Recipes");
        Button browseButton = new Button("Browse");
        Button searchButton = new Button("Search");
        Button groceryListButton = new Button("Grocery List");
        Button futureButton = new Button("Plan Future Meals");
        Button profileButton = new Button("Profile");
        tempForm.add(recommended);
        tempForm.add(savedRecipesButton);
        tempForm.add(browseButton);
        tempForm.add(searchButton);
        tempForm.add(groceryListButton);
        tempForm.add(futureButton);
        tempForm.add(profileButton);

        futureButton.addActionListener((e) -> futurePlanningForm.show());
        savedRecipesButton.addActionListener((e) -> savedRecipesForm.show());
        profileButton.addActionListener((e) -> profileForm.show());

        mainMenuForm = tempForm;
    }

    public void setFuturePlanningForm() {
        Form tempForm = new Form("Plan Future Meals", BoxLayout.y());
        Button homeButton = new Button("Home");
        tempForm.add(homeButton);
        homeButton.addActionListener((e) -> mainMenuForm.show());

        futurePlanningForm = tempForm;
    }

    public void setSavedRecipesForm() {
        Form tempForm = new Form("Saved Recipes", BoxLayout.y());
        Button homeButton = new Button("Home");
        Button myRecipesButton = new Button("My Recipes");
        Button customButton = new Button("Add Custom Recipe");
        Button favoriteButton = new Button("Favorite Recipes");
        tempForm.add(homeButton);
        tempForm.add(myRecipesButton);
        tempForm.add(customButton);
        tempForm.add(favoriteButton);
        homeButton.addActionListener((e) -> mainMenuForm.show());
        myRecipesButton.addActionListener((e) -> myRecipesForm.show());
        customButton.addActionListener((e) -> addCustomRecipeForm.show());
        favoriteButton.addActionListener((e) -> favoriteRecipesForm.show());

        savedRecipesForm = tempForm;
    }

    public void setMyRecipesForm() {
        Form tempForm = new Form("My Recipes", BoxLayout.y());
        Button homeButton = new Button("Home");
        Button backButton = new Button("Back");
        tempForm.add(homeButton);
        tempForm.add(backButton);
        homeButton.addActionListener((e) -> mainMenuForm.show());
        backButton.addActionListener((e) -> savedRecipesForm.show());

        myRecipesForm = tempForm;
    }

    public void setAddCustomRecipeForm() {
        Form tempForm = new Form("Add Custom Recipe", BoxLayout.y());
        Button homeButton = new Button("Home");
        Button backButton = new Button("Back");
        tempForm.add(homeButton);
        tempForm.add(backButton);
        homeButton.addActionListener((e) -> mainMenuForm.show());
        backButton.addActionListener((e) -> savedRecipesForm.show());

        addCustomRecipeForm = tempForm;
    }

    public void setFavoriteRecipesForm() {
        Form tempForm = new Form("Favorite Recipes", BoxLayout.y());
        Button homeButton = new Button("Home");
        Button backButton = new Button("Back");
        tempForm.add(homeButton);
        tempForm.add(backButton);
        homeButton.addActionListener((e) -> mainMenuForm.show());
        backButton.addActionListener((e) -> savedRecipesForm.show());

        favoriteRecipesForm = tempForm;
    }

    public void setProfileForm() {
        Form tempForm = new Form("Profile", BoxLayout.y());
        Button homeButton = new Button("Home");

        tempForm.add(homeButton);

        homeButton.addActionListener((e) -> mainMenuForm.show());

        profileForm = tempForm;
    }

    public void setNewUserForm() {
        Form tempForm = new Form("New User", BoxLayout.y());
        SpanLabel welcome = new SpanLabel("Welcome! Please answer a few questions so our app can better recommend you meals that fit your preferences. These options can be set later in your Profile.");

        Label cuisineLabel = new Label("Click below to pick your favorite cuisines");
        Button cuisineButton = new Button("Favorite Cuisines");

        Label allergiesLabel = new Label("Click below if you have any allergies");
        Button allergiesButton = new Button("Allergies");

        Label doneLabel = new Label("When finished, hit Done");
        Button doneButton = new Button("Done");

        tempForm.add(welcome);
        tempForm.add(cuisineLabel);
        tempForm.add(cuisineButton);
        tempForm.add(allergiesLabel);
        tempForm.add(allergiesButton);
        tempForm.add(doneLabel);
        tempForm.add(doneButton);
        
       // Label tester = new Label(currentUser.getLikedCuisines().toString());
       // tempForm.add(tester);

        cuisineButton.addActionListener((e) -> favoriteCuisinesForm.show());
        allergiesButton.addActionListener((e) -> allergiesForm.show());
        doneButton.addActionListener((e) -> mainMenuForm.show());

        newUserForm = tempForm;
    }

    public void setFavoriteCuisineForm() {
        Form tempForm = new Form("Favorite Cuisines", BoxLayout.y());

        Label favoriteLabel = new Label("Please check your favorite cuisines.");
        ArrayList<CheckBox> cuisineCheckBoxes = new ArrayList<>();
        for (String a : cuisineTypes) {
            cuisineCheckBoxes.add(new CheckBox(a));
        }

        Button backButton = new Button("Back");

        tempForm.add(favoriteLabel);
        for (CheckBox c : cuisineCheckBoxes) {
            tempForm.add(c);
        }
        tempForm.add(backButton);

        backButton.addActionListener((e)
                -> {            
            for (CheckBox c : cuisineCheckBoxes) {
                if (c.isSelected()) {
                    currentUser.addLikedCuisine(c.getName());
                }
            }
            System.out.println(currentUser.getLikedCuisines().toString());
            newUserForm.show();
        });

        favoriteCuisinesForm = tempForm;
    }

    public void setAllergiesForm() {
        Form tempForm = new Form("Allergies", BoxLayout.y());

        Button backButton = new Button("Back");

        tempForm.add(backButton);

        backButton.addActionListener((e) -> newUserForm.show());

        allergiesForm = tempForm;
    }

    public void setUpForms() {
        setMainMenuForm();
        setFuturePlanningForm();
        setSavedRecipesForm();
        setMyRecipesForm();
        setAddCustomRecipeForm();
        setFavoriteRecipesForm();
        setNewUserForm();
        setFavoriteCuisineForm();
        setAllergiesForm();
        setProfileForm();

    }

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {

        setUpForms();

        if (currentUser.isNewUser()) {
            newUserForm.show();
        } else {
            mainMenuForm.show();
        }

    }

    public void stop() {
        currentForm = getCurrentForm();
        if (currentForm instanceof Dialog) {
            ((Dialog) currentForm).dispose();
            currentForm = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
