package MealThymePlanner;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.codename1.ui.table.TableLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MealThymePlanner {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        //Main Menu Screen
        Form mainMenu = new Form("Main Menu", new TableLayout(4, 2));
        mainMenu.add(new Label("Main Menu"));
        Button recommended = new Button(("Recommended For You"));
        Button savedRecipesButton = new Button(("Saved Recipes"));
        Button browseButton = new Button(("Browse"));
        Button searchButton = new Button(("Search"));
        Button groceryListButton = new Button(("Grocery List"));
        Button futureButton = new Button(("Plan Future Meals"));
        Button profileButton = new Button(("Profile"));
        mainMenu.add(recommended);
        mainMenu.add(savedRecipesButton);
        mainMenu.add(browseButton);
        mainMenu.add(searchButton);
        mainMenu.add(groceryListButton);
        mainMenu.add(futureButton);
        mainMenu.add(profileButton);  
        
        //Future Planning Screen
        Form futurePlanning = new Form("Plan Future Meals", BoxLayout.y());        
        Button homeButton = new Button(("Home"));
        futurePlanning.add(homeButton);
        homeButton.addActionListener((e) -> mainMenu.show());
        
        //Saved Recipes Screen
        Form savedRecipes = new Form("Saved Recipes", BoxLayout.y());        
        Button homeButton2 = new Button(("Home"));
        Button myRecipesButton = new Button(("My Recipes"));
        Button customButton = new Button(("Add Custom Recipe"));
        Button favoriteButton = new Button(("Favorite Recipes"));
        savedRecipes.add(homeButton2);
        savedRecipes.add(myRecipesButton);
        savedRecipes.add(customButton);
        savedRecipes.add(favoriteButton);
        homeButton2.addActionListener((e) -> mainMenu.show());
        
        //Main Menu Screen cont.
        futureButton.addActionListener((e) -> futurePlanning.show());
        savedRecipesButton.addActionListener((e) -> savedRecipes.show());
        mainMenu.show();       
        
        
        // recommended.addActionListener((e) -> Dialog.show("Dialog Title", "hi", "OK", null));
        
        
        
        
        
        
        
        
        
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
